#!/bin/bash -e

# https://irq5.io/2016/12/22/raspberry-pi-zero-as-multiple-usb-gadgets/

#LOG="/home/pi/usb.log"

#echo "Starting" > $LOG

modprobe libcomposite
 
cd /sys/kernel/config/usb_gadget/
mkdir g && cd g
 
echo 0x1d6b > idVendor  # Linux Foundation
echo 0x0104 > idProduct # Multifunction Composite Gadget
echo 0x0100 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB    # USB 2.0
 
mkdir -p strings/0x409
echo "deadbeef00115599" > strings/0x409/serialnumber
echo "Greeshk"        > strings/0x409/manufacturer
echo "Pi Zero Gadget"   > strings/0x409/product

#echo "Wrote strings and descriptors" >> $LOG

#mkdir -p functions/acm.usb0    # serial
mkdir -p functions/ecm.usb0  # network
mkdir -p functions/ffs.usb0

#echo "Created function dirs:" >> $LOG
#ls -l functions >> $LOG

mkdir -p configs/c.1
echo 250 > configs/c.1/MaxPower
ln -s functions/ecm.usb0 configs/c.1/
ln -s functions/ffs.usb0 configs/c.1/
#ln -s functions/acm.usb0   configs/c.1/

#echo "Created configs:" >> $LOG
#ls -lR configs >> $LOG

mkdir /dev/ffs-usb0
mount -t functionfs usb0 /dev/ffs-usb0

#echo "Mounted /dev/ffs-usb0" >> $LOG
#gcc /home/pi/usb_init.c -o /home/pi/usb_init
usb_init &
#ls -l /dev/ffs-usb0 >> $LOG

udevadm settle -t 5 || :
ls /sys/class/udc/ > UDC

#echo "Done?.." >> $LOG

#dmesg >> $LOG
